title: PDB blog
author: marcandregirard
description: > # this means to ignore newlines until "baseurl:"
  On the adventure of creating a browser, I'm writing here everything I'm learning

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
